// <auto-generated />
using System;
using GraphqlApi.Entities.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GraphqlApi.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20191011100930_InitDatabase")]
    partial class InitDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GraphqlApi.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<Guid>("OwnerId");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("02a6c107-ec35-40d8-ad9e-30e618b570d3"),
                            Description = "Cash account for our users",
                            OwnerId = new Guid("4e78f187-56f2-4d4c-b1ca-130457381e0a"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("95b7ca9e-deca-41a8-8349-a932d0c5cc97"),
                            Description = "Savings account for our users",
                            OwnerId = new Guid("96a55f04-a4b2-4d89-8727-0a73c109ba0b"),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("8dbbeab3-9286-4ea2-b43b-a58829959e3f"),
                            Description = "Income account for our users",
                            OwnerId = new Guid("96a55f04-a4b2-4d89-8727-0a73c109ba0b"),
                            Type = 3
                        });
                });

            modelBuilder.Entity("GraphqlApi.Entities.Owner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4e78f187-56f2-4d4c-b1ca-130457381e0a"),
                            Address = "John Doe's address",
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = new Guid("96a55f04-a4b2-4d89-8727-0a73c109ba0b"),
                            Address = "Jane Doe's address",
                            Name = "Jane Doe"
                        });
                });

            modelBuilder.Entity("GraphqlApi.Entities.Account", b =>
                {
                    b.HasOne("GraphqlApi.Entities.Owner", "Owner")
                        .WithMany("Accounts")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
